# LOCAL
spring:
  application:
    name: saj-history-service-api
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://root:example@192.168.0.8:27017/saj_historico?authSource=admin
  kafka:
    bootstrap-servers: 192.168.0.8:9092
    consumer:
      group-id: history-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8081  # porta diferente do SAJ-API

kafka:
  topics:
    user-events: user-events

logging:
  level:
    com.software.saj_history_service: INFO
    org.springframework.boot.autoconfigure.mongo: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    prg.mongodb.driver.cluster: WARN
    org.mongodb.driver: WARN
