# LOCAL
# O spring não consegue pegar as informações do arquivo .env ao rodar no intelij, necessário colocar parametros default
spring:
  application:
    name: saj-history-service-api
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/saj_historico?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: history-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8081  # porta diferente do SAJ-API

logging:
  level:
    com.software.saj_history_service: INFO
    org.springframework.boot.autoconfigure.mongo: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: DEBUG
